#pragma once

// Extras menu: inserting emojis into the picture.

#include <QColor>
#include <QDialog>
#include <QImage>
#include <QStringList>

class QComboBox;
class QLabel;
class QLineEdit;
class QListView;
class QSortFilterProxyModel;
class QSpinBox;
class QStandardItemModel;
class QTabBar;

namespace app {

// Renders an emoji on a transparent square of `size` pixels. Monochrome emoji fonts use `color`.
QImage renderEmoji(const QString& emoji, int size, const QColor& color);

struct EmojiEntry {
    QString emoji;
    QString name;      // English (CLDR / Unicode)
    QStringList tones; // light ... dark skin-tone variants, or empty
    int group = 0;
    QString searchText; // lower-case, accents removed: localized + English names and keywords
};

// The full Unicode emoji list (resources/emoji, generated by scripts/gen_emoji.py),
// restricted to what the installed emoji font can draw.
class EmojiCatalog {
public:
    static const EmojiCatalog& instance();
    const QStringList& groups() const { return groups_; }
    const QList<EmojiEntry>& entries() const { return entries_; }

private:
    EmojiCatalog();
    QStringList groups_;
    QList<EmojiEntry> entries_;
};

// Lower-case text without accents, for accent-insensitive search.
QString searchKey(const QString& text);

class EmojiDialog : public QDialog {
    Q_OBJECT
public:
    explicit EmojiDialog(const QColor& color, QWidget* parent = nullptr);
    QString emoji() const;
    int emojiSize() const;
    void accept() override;

private:
    void applyFilter();
    void applyTone();
    void updatePreview();
    QStringList recent() const;

    QColor color_;
    QLineEdit* search_;
    QComboBox* tone_;
    QTabBar* tabs_;
    QListView* view_;
    QStandardItemModel* model_;
    QSortFilterProxyModel* proxy_;
    QLineEdit* custom_;
    QSpinBox* size_;
    QLabel* preview_;
    bool hasRecent_ = false;
};

} // namespace app
